name: Docker Image CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Docker tag
        id: tag
        uses: cytopia/docker-tag-action@v0.4.22
        with:
          latest_git_branch: main

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ghcr.io/jazzxp/shortener:${{ steps.tag.outputs.docker-tag }}

      - name: Push to registry
        run: docker push ghcr.io/jazzxp/shortener:${{ steps.tag.outputs.docker-tag }}
